// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  aws_project_region: 'ap-south-1',
  aws_appsync_graphqlEndpoint: 'https://xubepe5hkrfs7n4bdtvpwbkypm.appsync-api.ap-south-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-south-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-xweko33gsjg47cg4x74mecmxy4'
};


export default config;
