//------------------------------------------EULERS PROBLEM 2------------------------------------------
//------------------------------------------------------------------------------------

// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

//------------------------------------------FUNCTIONS------------------------------------------

const isEven = num => !(num % 2);

//------------------------------------------INPUT------------------------------------------

let limit = 4000000;

//------------------------------------------CORE CODE------------------------------------------

let num1 = 1,
  num2 = 2,
  sum = 0;
while (num2 <= limit) {
  if (isEven(num2)) sum += num2;
  let temp = num2;
  num2 += num1;
  num1 = temp;
}

//------------------------------------------OUTPUT------------------------------------------

console.log(sum);

//------------------------------------------------------------------------------------
